_name_: dnalongbench_450k
data_root: data/raw/dnalongbench
task_name: etgp
subset: null
train_val_split_seed: 1
tokenizer_name: char
d_output: 2
max_length: 450000
use_padding: true
padding_side: right
add_eos: false
batch_size: 1
batch_size_eval: 1
num_workers: 0
shuffle: true
shuffle_eval: false
pin_memory: true
drop_last: false
rc_aug: false
reverse_aug: false
conjoin_train: false
conjoin_test: false
reverse_val: false
reverse_test: false
return_anchor_metadata: false
__l_max: ${.max_length}
